/***************************************************************
    *  DO NOT EDIT THIS FILE!
    *         
    *  This file is automatically generated by HP Service Test.
    *  Manually changing the contents of this file may result in 
    *  loss of information.
    *          
    *  To edit the test, open the file ‘TesteRegistro.st’ 
    *  in HP Service Test.
     ***************************************************************/
    
    namespace Script
    {
    using System;
    using System.Text;
    using System.Threading;
    using System.Xml;
    using System.Xml.Schema;
    using HP.ST.Fwk.ReporterFWK;
    using HP.ST.Shared.Utilities;
    using HP.ST.Ext.BindingImpl.Getters;
    using HP.ST.Ext.BindingImpl.Setters;
    using HP.ST.Fwk.RunTimeFWK.BindingFWK;
    using HP.ST.Fwk.RunTimeFWK.BindingFWK.PropInfo;
    using HP.ST.Fwk.RunTimeFWK.BindingFWK.Getters;
    using HP.ST.Fwk.RunTimeFWK.BindingFWK.Setters;
    using HP.ST.Fwk.RunTimeFWK;
    using HP.ST.Fwk.RunTimeFWK.Utilities;
    using HP.ST.Fwk.RunTimeFWK.HelperClasses;
    using HP.ST.Fwk.RunTimeFWK.CompositeActivities;
    using HP.ST.Ext.BindingImpl.Setters.DataSourceSetters;
    using HP.ST.Fwk.JVMLoader;
    using System.IO;
    using System.Collections.Generic;
    using System.Reflection;
    using HP.ST.Fwk.SOAReplayAPI;
    using HP.ST.Fwk.UFTLicensing;
    
    
    
    public partial class WorkFlowScript : STWorkFlowScriptBase
    {    
    	TestUserCode _userCode = null;
    	TestEntities _flow = null;
    	static Reporter reporter;
    	int reportLevelInTree;
        HP.ST.Fwk.ReportCreator.QTPEngine.QTPEngineReportCreator reportCreator;
    	
    	public BindDirection bind_dir328 = null;
        public BindDirection bind_dir329 = null;
        public HP.ST.Ext.BasicActivities.DataCursorActivity DataCursorActivity10 = null;
        public BindDirection bind_dir330 = null;
        public HP.ST.Fwk.SOAReplayAPI.DataHandling.CursorMovementPolicy DataCursorActivity10_Policy = null;
        public BindDirection bind_dir331 = null;
        public BindDirection bind_dir332 = null;
        public BindDirection bind_dir333 = null;
        public BindDirection bind_dir334 = null;
        
        public IEnumerable<FeaturesGroup> LicensedFeatures
        {
        
        get
        {
        List<FeaturesGroup> features = new List<FeaturesGroup>();
        return features;
        
        }
        
        }
        
        public WorkFlowScript()
            : base(VuserClass.CommandLineArguments, new STRunTimeContext(), "test")
        {	
        	UpdateContextWithActionFolder(String.Empty);
        	
        }
        
        public WorkFlowScript(ISTRunTimeContext ctx)
            : base(VuserClass.CommandLineArguments, ctx, "test")
            
        {
        	this._context = ctx;
        	UpdateContextWithActionFolder(String.Empty);
        	UpdateTestSettings(ctx);
        }
        
        internal void InitializeComponent()
        {
        	LoadInput();
        	
        	InitReport();
        	
        	InitializeEncryptionManagerValues();
        
        	_userCode = new TestUserCode();
            _flow = _userCode;
            _flow.Context=this._context;
            
            
        
        	_flow.DataFetchActivity6 = new HP.ST.Ext.BasicActivities.DataFetchActivity(_context,"DataFetchActivity6");
            _flow.StartActivity1 = new HP.ST.Ext.BasicActivities.StartActivity(_context,"StartActivity1");
            _flow.Loop2 = new HP.ST.Fwk.RunTimeFWK.CompositeActivities.Loop<Loop2Input>(_context,"Loop2",LoopType.ForEach);
            _flow.DataExporterActivity8 = new HP.ST.Ext.BasicActivities.DataExporterActivity(_context,"DataExporterActivity8");
            _flow.DataExporterCloseActivity9 = new HP.ST.Ext.BasicActivities.DataExporterCloseActivity(_context,"DataExporterCloseActivity9");
            _flow.EndActivity3 = new HP.ST.Ext.BasicActivities.EndActivity(_context,"EndActivity3");
            _flow.DataDisconnectActivity7 = new HP.ST.Ext.BasicActivities.DataDisconnectActivity(_context,"DataDisconnectActivity7");
            this.DataCursorActivity10 = new HP.ST.Ext.BasicActivities.DataCursorActivity(_context,"DataCursorActivity10");
            this.DataCursorActivity10_Policy = new HP.ST.Fwk.SOAReplayAPI.DataHandling.CursorMovementPolicy();
            _flow.Sequence5 = new HP.ST.Fwk.RunTimeFWK.CompositeActivities.Sequence(_context,"Sequence5");
            _flow.HTTPActivity4 = new HP.ST.Ext.HTTPActivity.HTTPActivity(_context,"HTTPActivity4");
            _flow.DataFetchActivity6.Comment = @"";
            _flow.DataFetchActivity6.IconPath = @"";
            _flow.DataFetchActivity6.AssemblyPath = @"AddIns\ServiceTest\BaseDataProviders\HP.ST.Ext.CustomDataProviders.dll";
            _flow.DataFetchActivity6.QueryClassName = @"HP.ST.Ext.CustomDataProviders.LocalDataQuery";
            XmlDocument DataFetchActivity6_QueryParameters_Document = new XmlDocument();
            DataFetchActivity6_QueryParameters_Document.PreserveWhitespace = true;
            string xmlDataFetchActivity6Params = @"<Arguments><QueryParametersContainer><QueryParameter><Name>Id</Name><Value>9f722667-938f-4019-b0d0-13659d155510</Value></QueryParameter><QueryParameter><Name>QueryName</Name><Value>Registro</Value></QueryParameter><QueryParameter><Name>IsEmbedded</Name><Value>True</Value></QueryParameter><QueryParameter><Name>Externalized</Name><Value>False</Value></QueryParameter><QueryParameter><Name>GroupText</Name><Value></Value></QueryParameter><QueryParameter><Name>TableStructure</Name><Value>firstname,String,|lastname,String,|username,String,|password,String,</Value></QueryParameter><QueryParameter><Name>TableContents</Name><Value>Fernanda|Zimmer|feZimmer|1234^Lucas|Silva|luSilva|1234^Luciana|Alves|luAlves|1234</Value></QueryParameter></QueryParametersContainer></Arguments>";
            DataFetchActivity6_QueryParameters_Document.LoadXml(xmlDataFetchActivity6Params);
            _flow.DataFetchActivity6.QueryParameters = DataFetchActivity6_QueryParameters_Document;
            _flow.dataSourceNameToDataSource.Add("Registro", _flow.DataFetchActivity6);
            this.Activities.Add (_flow.DataFetchActivity6);
            _flow.StartActivity1.Comment = @"";
            _flow.StartActivity1.IconPath = @"AddIns\ServiceTest\BasicActivities\toolbox_code_activity.png";
            _flow.StartActivity1.Name = @"Start";
            _flow.StartActivity1.JVM = new HP.ST.Ext.BasicActivities.JVMProperties();
            _flow.StartActivity1.IsJavaUsed = false;
            _flow.StartActivity1.JVM.Classpath = @"%CLASSPATH%";
            _flow.StartActivity1.JVM.AdditionalVMParameters = @"";
            _flow.StartActivity1.JMS = new HP.ST.Ext.BasicActivities.JMSProperties();
            _flow.StartActivity1.IsJmsUsed = false;
            _flow.StartActivity1.JMS.JNDIContextFactory = @"<Select...>";
            _flow.StartActivity1.JMS.JNDIProviderUrl = @"";
            _flow.StartActivity1.JMS.JMSConnectionFactory = @"";
            _flow.StartActivity1.JMS.SecurityPrincipal = @"";
            _flow.StartActivity1.JMS.SecurityCredentials = @"";
            _flow.StartActivity1.JMS.JMSClientID = @"";
            _flow.StartActivity1.JMS.SSLPassword = @"";
            _flow.StartActivity1.JMS.SSLTrustedCertificate = @"";
            _flow.StartActivity1.JMS.SSLIdentity = @"";
            _flow.StartActivity1.JMS.ConnectionsPerProcess = @"1";
            _flow.StartActivity1.JMS.TimeoutOptions = @"DN_User_defined_Timeout";
            _flow.StartActivity1.JMS.UserTimeout = @"20";
            _flow.StartActivity1.JMS.GenerateAutoSelector = @"No";
            _flow.StartActivity1.KafkaSSL = new HP.ST.Fwk.KafkaFWK.KafkaSSLProperties();
            _flow.StartActivity1.IsKafkaUsed = false;
            _flow.StartActivity1.KafkaSSL.StrEnableSSL = @"No";
            _flow.StartActivity1.KafkaSSL.SSLCALocation = @"";
            _flow.StartActivity1.KafkaSSL.SSLClientCertificateLocation = @"";
            _flow.StartActivity1.KafkaSSL.SSLClientKeyLocation = @"";
            _flow.StartActivity1.KafkaSASL = new HP.ST.Fwk.KafkaFWK.KafkaSASLProperties();
            _flow.StartActivity1.KafkaSASL.StrEnableSASL = @"No";
            _flow.StartActivity1.KafkaSASL.StrMechanism = @"GSSAPI";
            _flow.StartActivity1.KafkaSASL.StrServiceName = @"";
            this.Activities.Add (_flow.StartActivity1);
            _flow.Loop2.ConditionAsString = @"For each item in {DataSource.Registro}";
            _flow.Loop2.NumberOfIterations = (int)1;
            _flow.Loop2.Condition += delegate(object sender,STActivityBaseEventArgs e)
            {
            return !DataCursorActivity10.IsAtEndPosition;
            };
            _flow.Loop2.Comment = @"";
            _flow.Loop2.IconPath = @"AddIns\ServiceTest\BasicActivities\toolbox_loop.png";
            _flow.Loop2.Name = @"Test Flow";
            _flow.Loop2.Activities.Add (this.DataCursorActivity10);
            _flow.Loop2.Activities.Add (_flow.Sequence5);
            this.Activities.Add (_flow.Loop2);
            _flow.DataExporterActivity8.Comment = @"";
            _flow.DataExporterActivity8.IconPath = @"";
            VTDPropertyInfoBase pi655 = new VTDPropertyInfoBase("OutTable");
            VTDBaseGetter binding_getter328 = new VTDObjectGetter(pi655);
            VTDPropertyInfoBase pi656 = new VTDPropertyInfoBase("Data");
            VTDBaseSetter binding_setter328 = new VTDObjectSetter(pi656);
            binding_setter328 = new StringFormaterDecorator(binding_setter328,"{Step.DataFetchActivity6.OutTable}");
            bind_dir328 = new BindDirection(_flow.DataFetchActivity6,binding_getter328,binding_setter328,BindTargetType.ToInProperty);
            _flow.DataExporterActivity8.InDirections.Add(bind_dir328);
            this.Activities.Add (_flow.DataExporterActivity8);
            _flow.DataExporterCloseActivity9.Comment = @"";
            _flow.DataExporterCloseActivity9.IconPath = @"";
            this.Activities.Add (_flow.DataExporterCloseActivity9);
            _flow.EndActivity3.Comment = @"";
            _flow.EndActivity3.IconPath = @"AddIns\ServiceTest\BasicActivities\toolbox_code_activity.png";
            _flow.EndActivity3.Name = @"End";
            this.Activities.Add (_flow.EndActivity3);
            _flow.DataDisconnectActivity7.Comment = @"";
            _flow.DataDisconnectActivity7.IconPath = @"";
            VTDPropertyInfoBase pi657 = new VTDPropertyInfoBase("OutTable");
            VTDBaseGetter binding_getter329 = new VTDObjectGetter(pi657);
            VTDPropertyInfoBase pi658 = new VTDPropertyInfoBase("Data");
            VTDBaseSetter binding_setter329 = new VTDObjectSetter(pi658);
            binding_setter329 = new StringFormaterDecorator(binding_setter329,"{Step.DataFetchActivity6.OutTable}");
            bind_dir329 = new BindDirection(_flow.DataFetchActivity6,binding_getter329,binding_setter329,BindTargetType.ToInProperty);
            _flow.DataDisconnectActivity7.InDirections.Add(bind_dir329);
            this.Activities.Add (_flow.DataDisconnectActivity7);
            this.DataCursorActivity10.Comment = @"";
            this.DataCursorActivity10.IconPath = @"";
            VTDPropertyInfoBase pi659 = new VTDPropertyInfoBase("OutTable");
            VTDBaseGetter binding_getter330 = new VTDObjectGetter(pi659);
            VTDPropertyInfoBase pi660 = new VTDPropertyInfoBase("InTable");
            VTDBaseSetter binding_setter330 = new VTDObjectSetter(pi660);
            binding_setter330 = new StringFormaterDecorator(binding_setter330,"{Step.DataFetchActivity6.OutTable}");
            bind_dir330 = new BindDirection(_flow.DataFetchActivity6,binding_getter330,binding_setter330,BindTargetType.ToInProperty);
            this.DataCursorActivity10.InDirections.Add(bind_dir330);
            this.DataCursorActivity10_Policy.StartPosition = CursorStartPosition.FirstRecord;
            this.DataCursorActivity10_Policy.StartAtSpecificRow = 1;
            this.DataCursorActivity10_Policy.StartCondition.ColumnName = "";
            this.DataCursorActivity10_Policy.StartCondition.Comparison = ConditionOperator.Equal;
            this.DataCursorActivity10_Policy.StartCondition.Value = "";
            this.DataCursorActivity10_Policy.EndPosition = CursorEndPosition.LastRecord;
            this.DataCursorActivity10_Policy.EndAtSpecificRow = 1;
            this.DataCursorActivity10_Policy.EndCondition.ColumnName = "";
            this.DataCursorActivity10_Policy.EndCondition.Comparison = ConditionOperator.Equal;
            this.DataCursorActivity10_Policy.EndCondition.Value = "";
            this.DataCursorActivity10_Policy.StepType = CursorStepType.Forward;
            this.DataCursorActivity10_Policy.StepSize = 1;
            this.DataCursorActivity10_Policy.ActionAfterLastRecord = CursorActionAfterLastRecord.Wraparound;
            this.DataCursorActivity10.Policy = this.DataCursorActivity10_Policy;
            this.DataCursorActivity10.ReportStepData = true;
            _flow.Loop2.BeforeExecuteStepEvent += this.DataCursorActivity10.ResetCursor;
            _flow.Sequence5.Comment = @"";
            _flow.Sequence5.IconPath = @"";
            _flow.Sequence5.Name = @"Sequence5";
            _flow.Sequence5.Activities.Add (_flow.HTTPActivity4);
            _flow.HTTPActivity4.TextBody = @"";
            _flow.HTTPActivity4.TextXmlBody = @"";
            _flow.HTTPActivity4.FileBody = @"";
            _flow.HTTPActivity4.PostBody = @"";
            _flow.HTTPActivity4.Url = @"http://localhost:3434/cars-app/register";
            _flow.HTTPActivity4.HttpMethod = @"POST";
            _flow.HTTPActivity4.HttpVersion = @"1.1";
            _flow.HTTPActivity4.RequestHeaders = new Pair<string, string>[1];
            _flow.HTTPActivity4.RequestHeaders[0] = new Pair<string, string>();
            _flow.HTTPActivity4.RequestHeaders[0].Key = @"Content-Type";
            _flow.HTTPActivity4.RequestHeaders[0].Value = @"application/json";
            _flow.HTTPActivity4.Comment = @"";
            _flow.HTTPActivity4.IconPath = @"AddIns\ServiceTest\HTTPActivity\toolbox_http.png";
            _flow.HTTPActivity4.RequestBodyType = @"Json";
            _flow.HTTPActivity4.ResponseType = @"Text";
            _flow.HTTPActivity4.Name = @"HTTP Request4";
            _flow.HTTPActivity4.Proxy.Server = @"";
            _flow.HTTPActivity4.Proxy.Username = @"";
            _flow.HTTPActivity4.Proxy.Password = @"";
            _flow.HTTPActivity4.Authentication.Username = @"";
            _flow.HTTPActivity4.Authentication.Password = @"";
            _flow.HTTPActivity4.Authentication.PreemptiveAuthentication = false;
            _flow.HTTPActivity4.ConnectionType = @"Keep-Alive";
            _flow.HTTPActivity4.Timeout = (int)100000;
            _flow.HTTPActivity4.ClientCertificate.Password = @"";
            _flow.HTTPActivity4.ClientCertificate.FileSystem.Path = @"";
            _flow.HTTPActivity4.UseClientCertificate = false;
            _flow.HTTPActivity4.MaximumAutomaticRedirections = (int)3;
            _flow.HTTPActivity4.AllowRedirections = true;
            _flow.HTTPActivity4.ReuseCookies = false;
            _flow.HTTPActivity4.ExpectServerError = false;
            _flow.HTTPActivity4.HanaRequest = false;
            XmlDocument HTTPActivity4_XMLBody_Document = new XmlDocument();
            HTTPActivity4_XMLBody_Document.PreserveWhitespace = true;
            HTTPActivity4_XMLBody_Document.LoadXml(
@"<Object jsonType=""Object"" isAnonymous=""true""><firstname jsonType=""String"">{DataSource.Registro.firstname}</firstname><lastname jsonType=""String"">{DataSource.Registro.lastname}</lastname><username jsonType=""String"">{DataSource.Registro.username}</username><password jsonType=""String"">{DataSource.Registro.password}</password></Object>");
            _flow.HTTPActivity4.XMLBody = HTTPActivity4_XMLBody_Document;
            XmlDocument HTTPActivity4_RequestMultipartInfoXml_Document = new XmlDocument();
            HTTPActivity4_RequestMultipartInfoXml_Document.PreserveWhitespace = true;
            HTTPActivity4_RequestMultipartInfoXml_Document.LoadXml(
@"<RequestMultipartInfo><Type>Related</Type></RequestMultipartInfo>");
            _flow.HTTPActivity4.RequestMultipartInfoXml = HTTPActivity4_RequestMultipartInfoXml_Document;
            _flow.HTTPActivity4.Multipart=false;
            VTDPropertyInfoBase pi661 = new VTDPropertyInfoBase("username");
            VTDBaseGetter binding_getter331 = new VTDObjectGetter(pi661);
            VTDPropertyInfoBase pi662 = new VTDPropertyInfoBase("XMLBody","/*[local-name(.)='Object'][1]/*[local-name(.)='username'][1]");
            VTDBaseSetter binding_setter331 = new VTDJsonSetter(pi662,XmlTypeCode.String);
            binding_setter331 = new StringFormaterDecorator(binding_setter331,"{DataSource.Registro.username}");
            bind_dir331 = new BindDirection(this.DataCursorActivity10,binding_getter331,binding_setter331,BindTargetType.ToInProperty);
            _flow.HTTPActivity4.InDirections.Add(bind_dir331);
            VTDPropertyInfoBase pi663 = new VTDPropertyInfoBase("password");
            VTDBaseGetter binding_getter332 = new VTDObjectGetter(pi663);
            VTDPropertyInfoBase pi664 = new VTDPropertyInfoBase("XMLBody","/*[local-name(.)='Object'][1]/*[local-name(.)='password'][1]");
            VTDBaseSetter binding_setter332 = new VTDJsonSetter(pi664,XmlTypeCode.String);
            binding_setter332 = new StringFormaterDecorator(binding_setter332,"{DataSource.Registro.password}");
            bind_dir332 = new BindDirection(this.DataCursorActivity10,binding_getter332,binding_setter332,BindTargetType.ToInProperty);
            _flow.HTTPActivity4.InDirections.Add(bind_dir332);
            VTDPropertyInfoBase pi665 = new VTDPropertyInfoBase("lastname");
            VTDBaseGetter binding_getter333 = new VTDObjectGetter(pi665);
            VTDPropertyInfoBase pi666 = new VTDPropertyInfoBase("XMLBody","/*[local-name(.)='Object'][1]/*[local-name(.)='lastname'][1]");
            VTDBaseSetter binding_setter333 = new VTDJsonSetter(pi666,XmlTypeCode.String);
            binding_setter333 = new StringFormaterDecorator(binding_setter333,"{DataSource.Registro.lastname}");
            bind_dir333 = new BindDirection(this.DataCursorActivity10,binding_getter333,binding_setter333,BindTargetType.ToInProperty);
            _flow.HTTPActivity4.InDirections.Add(bind_dir333);
            VTDPropertyInfoBase pi667 = new VTDPropertyInfoBase("firstname");
            VTDBaseGetter binding_getter334 = new VTDObjectGetter(pi667);
            VTDPropertyInfoBase pi668 = new VTDPropertyInfoBase("XMLBody","/*[local-name(.)='Object'][1]/*[local-name(.)='firstname'][1]");
            VTDBaseSetter binding_setter334 = new VTDJsonSetter(pi668,XmlTypeCode.String);
            binding_setter334 = new StringFormaterDecorator(binding_setter334,"{DataSource.Registro.firstname}");
            bind_dir334 = new BindDirection(this.DataCursorActivity10,binding_getter334,binding_setter334,BindTargetType.ToInProperty);
            _flow.HTTPActivity4.InDirections.Add(bind_dir334);
            XmlDocument HTTPActivity4_ExpectedResponseXmlBody_Document = new XmlDocument();
            HTTPActivity4_ExpectedResponseXmlBody_Document.PreserveWhitespace = true;
            HTTPActivity4_ExpectedResponseXmlBody_Document.LoadXml(
@"<F6DA54ED-92F5-4c5c-9795-170905F25080 />");
            _flow.HTTPActivity4.ExpectedResponseXmlBody = HTTPActivity4_ExpectedResponseXmlBody_Document;
            XmlDocument HTTPActivity4_ExpectedResponseJsonBody_Document = new XmlDocument();
            HTTPActivity4_ExpectedResponseJsonBody_Document.PreserveWhitespace = true;
            HTTPActivity4_ExpectedResponseJsonBody_Document.LoadXml(
@"<F6DA54ED-92F5-4c5c-9795-170905F25080 />");
            _flow.HTTPActivity4.ExpectedResponseJsonBody = HTTPActivity4_ExpectedResponseJsonBody_Document;
            XmlDocument HTTPActivity4_ExpectedOutputProperties_Document = new XmlDocument();
            HTTPActivity4_ExpectedOutputProperties_Document.PreserveWhitespace = true;
            HTTPActivity4_ExpectedOutputProperties_Document.LoadXml(
@"<Arguments><ResponseHttpVersion /><StatusCode>200</StatusCode><StatusDescription /><ResponseBody>status: success</ResponseBody><ResponseBodyAsBase64 /></Arguments>");
            _flow.HTTPActivity4.ExpectedOutputProperties = HTTPActivity4_ExpectedOutputProperties_Document;
            set_HTTPActivity4_checkpoints(_flow.HTTPActivity4);
            
        }
        
        internal void InitializeEncryptionManagerValues()
        {
        
        }
        	
    	bool useReport = true;
    
    	protected override STExecutionResult ExecuteStep()
        {
            return base.ExecuteStep();
        }
    
        public void Start()
        {
    	    try
    		{
    		  Workflow_Executing();
    		  this.ExecuteStep();
    		}
    		finally
    		{
    		  WorkFlowScript_Completed();
    		}
        }
    
    	private void InitReport()
    	{
    		if (useReport)
    		{	
    			// Intialize Reporter
    			string reportDBDir = Path.Combine(this._context.ReportDirectory, @"Report");
    			CleanupReport(reportDBDir);        	
    			string reportDBPath = Path.Combine(reportDBDir, "VTDReport.mdb");        	
    			if (reporter == null)
    			{
    				reporter = new Reporter(reportDBPath);
    			}
    			_context.Reporter = reporter;
    		}
    	}
    
        public static void CopyDirectory(string Src, string Dst)
        {
            String[] Files;
    
            if (Dst[Dst.Length - 1] != Path.DirectorySeparatorChar)
                Dst += Path.DirectorySeparatorChar;
            if (!Directory.Exists(Dst)) Directory.CreateDirectory(Dst);
            Files = Directory.GetFileSystemEntries(Src);
            foreach (string Element in Files)
            {
                // Sub directories
                if (Directory.Exists(Element))
                    CopyDirectory(Element, Dst + Path.GetFileName(Element));
                // Files in directory
                else
                    File.Copy(Element, Dst + Path.GetFileName(Element), true);
            }
        }
        
        private void CleanupReport(string reportDBDir)
        {   
    		if (useReport)
    		{             
    			string reportTemplateDir = Path.Combine(ServiceTestRunner.GetInstallPath(), "bin", "ReportResources");
    			try
    			{
            		CopyDirectory(reportTemplateDir, reportDBDir);
    			}
    			catch //(Exception ex)
    			{
    				//ToDo: LoggingService.Warn("Report Cleanup Error", ex);
    			}
    		}
        }
    
        void Workflow_Executing()
        {   
        	InitReportNode();
                       
        }
    
    	private void InitReportNode()
    	{
    		if (useReport)
    		{	
        		// Init report creator
    			this.reportCreator = new HP.ST.Fwk.ReportCreator.QTPEngine.QTPEngineReportCreator();
    			this.reportLevelInTree = reportCreator.Init(_context.EnvironmentProfile.GetVariableValue("TestName"), _context);
                
    			STActivityBase activity = this;
    			string workflowID = activity.GetHashCode().ToString();
    			ReportNodeCreationData newNodeData =
    			new ReportNodeCreationData(workflowID, workflowID, DateTime.Now);
    			reporter.CreateReportNode(newNodeData);
            
    			ReportInfoData newReportData = new ReportInfoData(workflowID, ReportKeywords.TypeKeywordTag, this.GetType().ToString());
    			reporter.SendReportData(newReportData);
    			newReportData = new ReportInfoData(workflowID, ReportKeywords.NameKeywordTag, this.Name);
    			//TrackData(ReportInfoData.InfoDataTag, newReportData);
    			reporter.SendReportData(newReportData);            
            }
    	}
        
        void WorkFlowScript_Completed()
        {   
    		
    
    		CreateReportFiles();
    					
        	// Write all snapshots to disk
    		this._context.SnapshotManager.WriteSnapshotsToDisk();
    
    		OnExecutionCompleted();
    		
        }
    
    	private void CreateReportFiles()
    	{
    		if (useReport)
    		{	
    			//Dispose reporter inorder to close connection to report DB
           		this._context.Reporter.Dispose();
            	
           		// Run report creator
    			reportCreator.RunOnDBAndCreateFiles();
    		}
    	}
    
        
        void Workflow_Faulting()
        {
    		
    
    		CreateReportFiles();
            // Write all snapshots to disk
    		this._context.SnapshotManager.WriteSnapshotsToDisk();
           
    		OnExecutionCompleted();
        }
    
    	protected override QcSystemVariables GetRuntimeQcVariables(ISTRunTimeContext context)
    	{
    		return new HP.ST.Ext.BasicActivities.RuntimeQcVariables(this._context);
    	}
            
    	protected override TestSystemVariables GetTestSystemVariables(ISTRunTimeContext context)
    	{
    		return new HP.ST.Ext.BasicActivities.RuntimeTestVariables(this._context);
    	}
    
    	private void UpdateTestSettings(ISTRunTimeContext ctx)
        {
    		ctx.PropertyBag["StopTestOnStepFailure"] = true;
    	}
    }
    
    public partial class VuserClass
    {
    	public static string[] CommandLineArguments;
    	public static string[] DotNetResolverPaths;
    	
        public VuserClass()
        {
    				
    		AssemblyResolver.AddSTPathsToResolutionPaths();
    		AssemblyResolver.AttachToAppdomain();
        }
    
        private void AddAssemblyResolver()
        {
    		AssemblyResolver.AddTestPathToResolutionPaths(GetTestPath());
    		AssemblyResolver.AddPathsForAssemblyResolution(DotNetResolverPaths);
        }
    	
        public int STAction()
        {	
            AddAssemblyResolver();
            STRunTimeContext ctx = new STRunTimeContext(Directory.GetParent(Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location)).FullName, string.Empty);
            WorkFlowScript script = new WorkFlowScript(ctx);
            script.InitializeComponent();
            script.Start();       
            
            return 0;
        }
        
        public void NotifyLicenseException(string msg)
        {
        		
    		try
    		{
    		    STRunTimeContext ctx = new STRunTimeContext(Directory.GetParent(Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location)).FullName, string.Empty);
                WorkFlowScript script = new WorkFlowScript(ctx);
                script.InitializeComponent();
                script.Context.ReplayClient.OnLicenseFailure(msg);
                
            }
            catch (Exception)
            {
    			// ToDo: log the error message
            }        
        }
    
    	 protected string GetTestPath()
            {
                if (CommandLineArguments != null)
                {
                    for (int i = 0; i < CommandLineArguments.Length; i++)
                    {
                        if (CommandLineArguments[i].Equals("-test", StringComparison.OrdinalIgnoreCase))
                        {
                            return CommandLineArguments[i + 1];
                        }
                    }
                }
                return String.Empty;
            }
        
    }
    
    }
    